config/routes.rb
Rails.application.routes.draw do
  root to: 'exercises#index'
  get 'ui(/:action)', controller: 'ui'

  get '/home', to: 'exercises#index'

  get '/register', to: 'users#new'

  resources :users, only: [:create]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/workout_complete', to: 'pages#workout_complete'
  get '/exercise_created_success', to: 'pages#exercise_created_success'
  get '/exercise_required', to: 'pages#exercise_required'

  resources :exercises do
    collection do
      post :update_multiple
    end
  end

  resources :workouts
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :workouts

  validates_presence_of :name, :user
  validates_presence_of :time_type, if: 'time'
  validates_presence_of :time, if: 'time_type && !time_type.empty?'
  validate :at_least_two_params

  def at_least_two_params
    if  exercise_param_size == 0 || exercise_param_size == 1
      errors[:base] << ("Please choose at least two workout paramaters")
    end
  end 

  def exercise_param_size
    [self.weight, self.time, self.sets, self.reps].reject(&:blank?).size
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :exercises
  has_many :workouts

  has_secure_password

  validates_presence_of :full_name
  validates_presence_of :username
  validates_uniqueness_of :username
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :exercises

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    redirect_to login_path unless current_user
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :require_user
  before_action :find_exercise, only: [:edit, :update, :destroy] 
  
  def index
    @exercises = current_user.exercises
  end

  def new
    @exercise = Exercise.new
  end

  def create
    @exercise = Exercise.new(exercise_params)
    @exercise.user = current_user

    if @exercise.save
      redirect_to exercise_created_success_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @exercise.update(exercise_params) 
      flash["notice"] = @exercise.name.titleize + " was updated successfully"
      redirect_to home_path
    else
      render :edit
    end
  end

  def destroy
    @exercise.destroy
    redirect_to home_path
  end

  def update_multiple
    begin
    update_exercises
    rescue ActiveRecord::RecordInvalid
      flash["danger"] = "Attributes must be valid"
    end
    redirect_to workout_complete_path
  end

  private

  def exercise_params
    params.require(:exercise).permit(:name, :weight, :time, :time_type, :sets, :reps, :user_id)
  end

  def find_exercise
    @exercise = Exercise.find params[:id]
  end

  def update_exercises
    ActiveRecord::Base.transaction do
      params[:exercises].each do |exercise_data|
        exercise = Exercise.find(exercise_data["id"])
        if exercise.user == current_user
          exercise.update!(weight: exercise_data["weight"], time: exercise_data["time"], sets: exercise_data["sets"], reps: exercise_data["reps"]) 
        end
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def front
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to home_path if current_user
  end

  def create
    user = User.find_by username: params[:username]

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to home_path
    else
      flash['danger'] = 'There was something wrong with your username or password.'
      redirect_to login_path
    end 
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController

  before_filter do
    redirect_to :root if Rails.env.production?
  end

  layout "application"

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :send_user_home

  def new 
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash["notice"] = "Welcome #{current_user.full_name}! You've successfully registered."
      redirect_to home_path
    else
      render :new
    end
  end

  private

  def send_user_home
    redirect_to home_path if logged_in?
  end

  def user_params
    params.require(:user).permit(:full_name, :username, :password, :password_confirmation)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :require_user
  before_action :find_workout, only: [:show, :edit, :update, :destroy]

  def index
    @workouts = current_user.workouts
  end

  def show
  end

  def new
    @workout = Workout.new
    require_exercises
  end

  def create
    @workout = Workout.new(workout_params)
    @workout.user_id = current_user.id

    if @workout.save
      put_exercises_into_workout
      flash["notice"] = "You've successfully added #{@workout.name.titleize}."
      redirect_to workouts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @workout.update_attributes(workout_params)
      put_exercises_into_workout
      flash["notice"] = "#{@workout.name.titleize} was edited successfully"
      redirect_to workouts_path
    else
      render :edit
    end
  end

  def destroy
    @workout.destroy
    redirect_to workouts_path
  end

  private

  def workout_params
    params.require(:workout).permit(:name, :exercise_ids => [])
  end

  def find_workout
    @workout = Workout.find params[:id]
  end

  def require_exercises
    if current_user.exercises.empty?
      redirect_to exercise_required_path
    end
  end

  def put_exercises_into_workout
    @workout.exercises.clear
    params[:workout][:exercises].reject(&:empty?).each do |exercise_id|
      exercise = Exercise.find exercise_id.to_i
      @workout.exercises << exercise
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercise_status_helper.rb
module ExerciseStatusHelper
  def display_current_exercise_status(exercise)
    string = ''
    string << exercise.weight.to_s + ' LBS' if exercise.weight
    string << ', ' if (!string.empty?)  && (!string.strip.end_with?(',')) && (exercise.time || exercise.sets || exercise.reps)
    string << exercise.time.to_s + ' ' + exercise.time_type if exercise.time
    string << ', ' if !string.empty? && !string.strip.end_with?(',') && (exercise.sets || exercise.reps)
    string << exercise.sets.to_s + ' Sets' if exercise.sets
    string << ', ' if !string.empty?  && !string.strip.end_with?(',') && (exercise.reps)
    string << exercise.reps.to_s + ' Reps' if exercise.reps
    string
  end
end

app/helpers/options_for_select_helper.rb
module OptionsForSelectHelper
  def options_for_weight(exercise)
    options_for_select((1..300).select { |n| n % 5 == 0 }.map(&:to_s), exercise.weight.to_s)
  end

  def options_for_time(exercise)
    options_for_select(one_through_sixty, exercise.time.to_s)
  end

  def options_for_time_type(exercise)
    options_for_select(["Seconds", "Minutes"], exercise.time_type)
  end

  def options_for_reps(exercise)
    options_for_select(one_through_sixty, exercise.reps.to_s)
  end

  def options_for_sets(exercise)
    options_for_select(one_through_fifteen, exercise.sets.to_s)
  end

  def one_through_sixty
    (1..60).map(&:to_s)
  end

  def one_through_fifteen
    (1..15).map(&:to_s)
  end
end

app/views/exercises/_form.html.haml
-if @exercise.errors.any?
  = render "shared/display_errors", obj: @exercise
= form_for @exercise, html: { class: "form-horizontal" } do |f|
  .col-sm-10.well.center.clearfix
    .form-group
      = f.label :name, "Exercise Name:", class: "col-sm-3 col-sm-offset-2 control-label"
      .col-sm-5
        = f.text_field :name, class: "form-control"
    .form-group
      = f.label :weight, "Weight:", class: "col-sm-3 col-sm-offset-2 control-label"
      .col-sm-2
        = f.select :weight, options_for_weight(@exercise), {include_blank: true}, { class: "form-control" }
    .form-group
      = f.label :time, "Time:", class: "col-sm-3 col-sm-offset-2 control-label"
      .col-sm-2
        = f.select :time, options_for_time(@exercise), {include_blank: true}, { class: "form-control" }
      .col-sm-2
        = f.select :time_type, options_for_time_type(@exercise), {include_blank: true}, { class: "form-control" }
    .form-group
      = f.label :sets, "Sets:", class: "col-sm-3 col-sm-offset-2 control-label"
      .col-sm-2
        = f.select :sets, options_for_sets(@exercise), {include_blank: true}, { class: "form-control" }
    .form-group
      = f.label :reps, "Reps:", class: "col-sm-3 col-sm-offset-2 control-label"
      .col-sm-2
        = f.select :reps, options_for_reps(@exercise), {include_blank: true}, { class: "form-control" }
    .col-sm-10.col-sm-offset-5.buttons
      = f.submit submit_type, class: "btn btn-success"
      -if cancel_or_delete == "delete"
        = link_to "Delete", exercise_path(@exercise), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class: "btn btn-danger"
      = link_to "Cancel", :back, class: "btn btn-warning"

app/views/exercises/edit.html.haml
%h3
  Edit Exercise
= render 'form', submit_type: "Edit", cancel_or_delete: "delete"

app/views/exercises/index.html.haml
%h3
  = "#{current_user.full_name.titleize}'s Exercises"
.col-sm-10.well.center
  -if @exercises.empty?
    .obj-empty-text
      %h4
        You don't have any exercises yet.
      %p
        To add an exercise, select New and then Exercise in the navigation up top.
  %dl.dl-horizontal
    - @exercises.each do |exercise|
      %dt
        = exercise.name.titleize + ":"
      %dd
        = display_current_exercise_status(exercise)
        = link_to "Edit", edit_exercise_path(exercise), class: "edit"
      - unless exercise == @exercises.last
        %br

app/views/exercises/new.html.haml
%h3
  Add Exercise
= render 'form', submit_type: "Create", cancel_or_delete: "cancel"

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title Fit Keeper
    %meta(charset="UTF-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = csrf_meta_tag
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
  %body
    %header
      = render 'shared/header' unless @take_out_header
    %section.content.clearfix
      .col-sm-8.center
        = render 'shared/messages'
    = yield

app/views/pages/exercise_created_success.html.haml
%h3
  Your Exercise was Created!!
.col-sm-2.center.success-buttons
  = link_to "Home", root_path, class: "btn btn-success"
  = link_to "Logout", logout_path, class: "btn btn-danger"

app/views/pages/exercise_required.html.haml
.obj-empty-text
  %h3
    Hold your horses...You don't have any exercises yet...
  %p
    Please create some new exercises before creating a new workout.
  .col-sm-2.center.success-buttons
    = link_to "New Exercise", new_exercise_path, class: "btn btn-success"
    = link_to "Cancel", root_path, class: "btn btn-danger"

app/views/pages/workout_complete.html.haml
%h3
  Congatulations!! You've Completed Your Workout.
.col-sm-2.center.success-buttons
  = link_to "Home", root_path, class: "btn btn-success"
  = link_to "Logout", logout_path, class: "btn btn-danger"

app/views/shared/_display_errors.html.haml
- if obj.errors.any?
  .alert.alert-danger.col-sm-10.center
    %h5 The following errors occured:
    %ul
      - obj.errors.full_messages.each do |message|
        %li= message

app/views/shared/_header.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      -if logged_in?
        %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
      = link_to 'FitKeeper', home_path, class: 'navbar-brand'
    - if logged_in?
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li
            = link_to "Workouts", workouts_path
          %li
            = link_to "Exercises", exercises_path
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              New +
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to "Workout", new_workout_path
              %li
                = link_to "Exercise", new_exercise_path 
          %li
            = link_to 'Logout', logout_path

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == "notice" ? "success" : "danger"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/ui/add_exercise.html.haml
%h3
  Add Exercise
.col-sm-10.well.center.clearfix
  %form.form-horizontal
    .form-group
      %label.col-sm-3.col-sm-offset-2.control-label
        Exercise Name:
      .col-sm-5
        %input.form-control
    .form-group
      %label.col-sm-3.col-sm-offset-2.control-label
        Weight:
      .col-sm-2
        %select.form-control
          %option
          %option 1
          %option 3
          %option 5
          %option 10
          %option 15
          %option 20
          %option 25
          %option 30
          %option 35
          %option 40
          %option 45
          %option 50
    .form-group
      %label.col-sm-3.col-sm-offset-2.control-label
        Time:
      .col-sm-2
        %select.form-control
          %option
          - (1..60).each do |num|
            %option 
              = num
      .col-sm-2
        %select.form-control
          %option
          %option Seconds
          %option Minutes
    .form-group
      %label.col-sm-3.col-sm-offset-2.control-label
        Sets:
      .col-sm-2
        %select.form-control
          %option
          - (1..60).each do |num|
            %option 
              = num
    .form-group
      %label.col-sm-3.col-sm-offset-2.control-label
        Reps:
      .col-sm-2
        %select.form-control
          %option
          - (1..60).each do |num|
            %option 
              = num
    .col-sm-10.col-sm-offset-5.buttons
      %button.btn.btn-success.submit{type: "submit"}
        Create
      %a.btn.btn-danger
        Cancel

app/views/ui/add_workout.html.haml
%h3
  Add Workout
.col-sm-10.well.center.clearfix
  %form.form-horizontal
    .form-group
      %label.col-sm-3.col-sm-offset-2.control-label
        Workout Name:
      .col-sm-5
        %input.form-control
    .form-group
      %label.col-sm-3.col-sm-offset-2.control-label
        Exercises:
      .col-sm-5
        %select#exercise-options.form-control{:multiple => "multiple"}
          %option Deadlifts
          %option Squats
          %option Pullups
          %option Planks
          %option Leglifts
          %option Curls
      .col-sm-10.col-sm-offset-5.buttons
        %button.btn.btn-success.submit{type: "submit"}
          Add
        %a.btn.btn-warning.submit
          Cancel
        %a.btn.btn-danger
          Delete

app/views/ui/edit_workout.html.haml
%h3
  Edit Workout
.col-sm-10.well.center.clearfix
  %form.form-horizontal
    .form-group
      %label.col-sm-3.col-sm-offset-2.control-label
        Workout Name:
      .col-sm-5
        %input.form-control
    .form-group
      %label.col-sm-3.col-sm-offset-2.control-label
        Exercises:
      .col-sm-5
        %select#exercise-options.form-control{:multiple => "multiple"}
          %option Deadlifts
          %option Squats
          %option Pullups
          %option Planks
          %option Leglifts
          %option Curls
      .col-sm-10.col-sm-offset-5.buttons
        %button.btn.btn-success.submit{type: "submit"}
          Submit
        %a.btn.btn-warning.submit
          Cancel
        %a.btn.btn-danger
          Delete

app/views/ui/home.html.haml
%h3
  Current Status
.col-sm-10.well.center
  %dl.dl-horizontal
    %dt
      Squats:
    %dd
      105 lb, 3 sets
    %br
    %dt
      Dead Lifts:
    %dd
      85 lb, 3 sets
    %br
    %dt
      Lower Back:
    %dd
      20 reps, 3 sets
    %br
    %dt
      Leg Extensions:
    %dd
      50 lb, 3 sets
    %br
    %dt
      Seated Leg:
    %dd
      55 lb, 3 sets
    %br
    %dt
      Pullups:
    %dd
      75 lb, 3 sets

app/views/ui/index.html.haml
%section
  %h3
    UI Links
  .well.col-sm-10.center
    %ul
      - Dir.glob('app/views/ui/*.html.haml').sort.each do |file|
        - wireframe = File.basename(file,'.html.haml')
        -  unless wireframe == 'index' || wireframe.match(/^_/)
          %li= link_to wireframe.titleize, action: wireframe unless wireframe == 'index'

app/views/ui/login.html.haml
.col-sm-8.well.center
  %h3
    Login
  %hr
  %form.form-horizontal
    .form-group
      %label.col-sm-2.control-label{:for => "inputusername3"} Username
      .col-sm-6
        %input#inputEmail3.form-control{:placeholder => "Username", :type => "text"}/
    .form-group
      %label.col-sm-2.control-label{:for => "inputPassword3"} Password
      .col-sm-6
        %input#inputPassword3.form-control{:placeholder => "Password", :type => "password"}/
    .form-group
      .col-sm-offset-2.col-sm-10
        %button.btn.btn-default{:type => "submit"} Sign in

app/views/ui/view_workout.html.haml
%h3
  Leg Day
.col-sm-10.well.center
  %form.form-horizontal
    .form-group.single-exercise
      %label.col-sm-2.col-sm-offset-1.control-label Dead Lifts
      .col-sm-2
        %select.form-control
          %option 5
          %option 10
          %option 15
          %option 20
          %option 25
          %option 30
          %option 35
          %option 40
          %option 45
          %option 50
      .col-sm-1
        %p LBS
      .col-sm-2
        %select.form-control
          %option 5
          %option 10
          %option 15
          %option 20
          %option 25
          %option 30
          %option 35
          %option 40
          %option 45
          %option 50
      .col-sm-1
        %p REPS
      .col-sm-1
        %a.btn.btn-success
          Done!
.col-sm-10.well.center
  %form.form-horizontal
    .form-group.single-exercise
      %label.col-sm-2.col-sm-offset-1.control-label Squats
      .col-sm-2
        %select.form-control
          %option 5
          %option 10
          %option 15
          %option 20
          %option 25
          %option 30
          %option 35
          %option 40
          %option 45
          %option 50
      .col-sm-1
        %p LBS
      .col-sm-2
        %select.form-control
          %option 5
          %option 10
          %option 15
          %option 20
          %option 25
          %option 30
          %option 35
          %option 40
          %option 45
          %option 50
      .col-sm-1
        %p REPS
      .col-sm-1
        %a.btn.btn-success
          Done!
.col-sm-10.well.center
  %form.form-horizontal
    .form-group.single-exercise
      %label.col-sm-2.col-sm-offset-1.control-label Lunges
      .col-sm-2
        %select.form-control
          %option 5
          %option 10
          %option 15
          %option 20
          %option 25
          %option 30
          %option 35
          %option 40
          %option 45
          %option 50
      .col-sm-1
        %p LBS
      .col-sm-2
        %select.form-control
          %option 5
          %option 10
          %option 15
          %option 20
          %option 25
          %option 30
          %option 35
          %option 40
          %option 45
          %option 50
      .col-sm-1
        %p REPS
      .col-sm-1
        %a.btn.btn-success
          Done!
.col-sm-10.well.center
  %form.form-horizontal
    .form-group.single-exercise
      %label.col-sm-2.col-sm-offset-1.control-label Leg Extensions
      .col-sm-2
        %select.form-control
          %option 5
          %option 10
          %option 15
          %option 20
          %option 25
          %option 30
          %option 35
          %option 40
          %option 45
          %option 50
      .col-sm-1
        %p LBS
      .col-sm-2
        %select.form-control
          %option 5
          %option 10
          %option 15
          %option 20
          %option 25
          %option 30
          %option 35
          %option 40
          %option 45
          %option 50
      .col-sm-1
        %p REPS
      .col-sm-1
        %a.btn.btn-success
          Done!
.col-sm-10.col-sm-offset-5
  %button.btn.btn-success.submit{type: "submit"}
    Workout Complete!
  %a.btn.btn-danger
    Cancel

app/views/ui/workouts.html.haml
%h3
  Workouts
.col-sm-10.well.center
  .workout.clearfix
    %h4
      Leg Day
    %a.btn.btn-warning{href: ""}
      Edit
    %a.btn.btn-success.start{href: ""}
      Start Workout
  .workout.clearfix
    %h4
      Chest and Abs
    %a.btn.btn-warning{href: ""}
      Edit
    %a.btn.btn-success.start{href: ""}
      Start Workout
  .workout.clearfix
    %h4
      Back and Shoulders
    %a.btn.btn-warning{href: ""}
      Edit
    %a.btn.btn-success.start{href: ""}
      Start Workout

app/views/users/new.html.haml
%h3
  Register
.col-sm-8.well.center
  = bootstrap_form_for @user, layout: :horizontal, label_col: "col-sm-3 col-sm-offset-1", control_col: "col-sm-6", method: 'post' do |f|
    = f.text_field :full_name, label: "Full Name"
    = f.text_field :username
    = f.password_field :password
    = f.password_field :password_confirmation, label: "Confirm Password"
    = f.submit 'Register', class: 'col-sm-offset-4 btn btn-default'
    %br
    %br
    %span.col-sm-offset-4
      Already a Member? 
      = link_to "Login Here", login_path

app/views/workouts/_display_exercise.html.haml
.form-group.single-exercise.col-sm-12
  = hidden_field_tag "exercises[][id]", exercise.id
  = label_tag exercise.name, nil,class: "col-sm-1 control-label"
  - if exercise.weight
    .col-sm-2
      = select_tag "exercises[][weight]", options_for_weight(exercise), class: "form-control"
    .col-sm-1.exercise-label
      %p LBS
  - if exercise.time
    .col-sm-2
      = select_tag "exercises[][time]", options_for_time(exercise), class: "form-control"
    .col-sm-1.exercise-label
      = exercise.time_type
  - if exercise.sets
    .col-sm-2
      = select_tag "exercises[][sets]", options_for_sets(exercise), class: "form-control"
    .col-sm-1.exercise-label
      %p SETS
  - if exercise.reps
    .col-sm-2
      = select_tag "exercises[][reps]", options_for_reps(exercise), class: "form-control"
    .col-sm-1.exercise-label
      %p REPS
  = image_tag "check.png", id: "check_#{exercise.id}"
  %btn.btn.btn-success.pull{id: "button_#{exercise.id}"}
    Done!
  :javascript
    $(document).ready(function() {
      $("#check_#{exercise.id}").hide();

      $("#button_#{exercise.id}").click(function(){
        $(this).hide();
        $("#check_#{exercise.id}").show();
      });
    });

app/views/workouts/_form.html.haml
.col-sm-10.well.center.clearfix
  = bootstrap_form_for @workout, layout: :horizontal, label_col: "col-sm-3 col-sm-offset-1", control_col: "col-sm-6" do |f|
    = f.text_field :name, label: "Workout Name"
    = f.collection_select :exercises, current_user.exercises.all, :id, :name, {include_blank: false, selected: @workout.exercises.map(&:id)}, { multiple: true, id: "exercise-options" }
    = f.submit submit_type, class: "btn btn-success col-sm-offset-4"
    -if cancel_or_delete == "delete"
      = link_to "Delete", workout_path(@workout), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class: "btn btn-danger"
    = link_to "Cancel", :back, class: "btn btn-warning"

app/views/workouts/edit.html.haml
%h3
  Edit Workout
= render "form", submit_type: "Edit", cancel_or_delete: 'delete'

app/views/workouts/index.html.haml
%h3
  = "#{current_user.full_name.titleize}'s Workouts"
.col-sm-10.well.center
  -if @workouts.empty?
    .obj-empty-text
      %h4
        You don't have any workouts yet.
      %p
        To add a workout, select New and then Workout in the navigation up top. Be sure to add exercises first so that you can add the exercises to the workout.
  - @workouts.each do |workout|
    .workout.clearfix
      %h4
        = workout.name.titleize
      = link_to "Edit", edit_workout_path(workout), class: "btn btn-warning"
      = link_to "Start Workout", workout_path(workout), class: "btn btn-success start"
    - unless workout == @workouts.last
      %hr

app/views/workouts/new.html.haml
%h3
  Add Workout
= render "form", submit_type: "Add Workout", cancel_or_delete: 'cancel'

app/views/workouts/show.html.haml
%h3
  = @workout.name.titleize
= form_tag update_multiple_exercises_path, class: 'form-horizontal' do
  .col-sm-10.well.center.clearfix
    -if @workout.exercises.empty?
      .obj-empty-text
        %h4
          = "#{@workout.name.titleize} doesn't have any exercises yet."
        %p
          = "To add an exercise to #{@workout.name.titleize}, navigate to workouts and then click edit"
    - @workout.exercises.each do |exercise|  
      = render 'display_exercise', exercise: exercise
  %div.col-sm-10.col-sm-offset-5
    = submit_tag "Workout Complete!", class: "btn btn-success submit"
    = link_to "Cancel", :back, class: "btn btn-danger"